### ISSUE TITLE
Get this into Bintray and Maven Central

### ISSUE THREAD

**Issue by rnorth** [rnorth/test-containers#1]

**Comment by rnorth** [comment]
It's in bintray as of yesterday.

**Comment by gusohal** [comment]
What is the current situation with Maven Central?

**Comment by rnorth** [comment]
v0.9.3 is in Maven Central but unfortunately I royally screwed up the
groupId.

v0.9.5, hopefully including your Oracle-XE and JDK7 PRs is what I'll try to
put in to Maven Central at the weekend.
