### ISSUE TITLE
Java 7 Compatibility

### ISSUE THREAD

**Issue by gusohal** [rnorth/test-containers#13]

**Comment by gusohal** [comment]
@rnorth - we need to consider this unfortunately!
Looks like the Java8 Specific stuff you have used are:

 - Lambdas - https://github.com/orfjackal/retrolambda
 - Streams - https://github.com/ReactiveX/RxJava
- Method References  - ?

**Comment by rnorth** [comment]
That's a shame. I think it's OK to support Java 7 for a few more months, though.

This shouldn't be too hard - I think the things you've identified are the main items, and none of them would suffer too much to be downgraded to JDK7.

I'd prefer not to drag in any third party libs to replace Java 8 features, though; they're only being used for conciseness, so there should be quite straightforward JDK7 fallbacks for the most part.

**Comment by gusohal** [comment]
Do you just want to roll the code back to JDK7 then, or do you want to branch this out?
