### ISSUE TITLE
Process around managing Github Issues

### ISSUE THREAD

**Issue by gusohal** [rnorth/test-containers#16]
We need to start prioritising the issues raised. I mentioned we could use waffle.io to do this. Any thoughts? @rnorth @haines @outofcoffee

**Comment by rnorth** [comment]
I think for now I'm content to use what Github gives us for now; labels for type/priority, and we should use milestones and assignees too. If this humble little project ever needs more that it'd be a nice problem to have!

I will take the action to categorise tickets this weekend though!
