### ISSUE TITLE
Automated tests - Circle CI

### ISSUE THREAD

**Issue by rnorth** [rnorth/test-containers#2]
If possible, use Travis, although use of docker will probably make this complex...

**Comment by gusohal** [comment]
CircleCI is the way to go as discussed. Do you want me to pick this up? @rnorth

**Comment by rnorth** [comment]
Yes please, but can we talk about it later today (my time) / tomorrow (your
time)?

**Comment by gusohal** [comment]
Sure

**Comment by rnorth** [comment]
I started playing around with this on a branch (circle-ci) but it's a little more complicated than first meets the eye - because we need to connect to the docker daemon via tcp, and that entails getting TLS set up.

This article (in German) seems to address exactly this scenario, so will probably be quite useful:

http://www.heise.de/developer/artikel/Abgesichert-Docker-auf-CircleCI-mit-TLS-ausfuehren-2574058.html

**Comment by swissarmykirpan** [comment]
Oooh fun!

**Comment by rnorth** [comment]
Now closed in df0f41b191dfbd38bc9c236b332543a4c0845eae
